# Generated by Django 4.2.7 on 2023-11-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_product_settings_client_client_logo_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client',
            new_name='client_invoice',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='product',
            new_name='product_invoice',
        ),
        migrations.AddField(
            model_name='client',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
