# Generated by Django 4.2.7 on 2023-11-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product_invoice',
        ),
        migrations.AddField(
            model_name='product',
            name='product_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice'),
        ),
    ]
